version: '2'
services:
  COMPARER:
    image: gds-comparer:1.0.0
    environment:
      COU: id
      PROD_DB_IP: 172.16.129.110
      PROD_DB_PORT: '1521'
      PROD_DB_SID: ORCL
      PROD_DB_USERNAME: a2d_id
      PROD_DB_PASSWORD: tiens
      BASE_DB_IP: 192.168.2.162
      BASE_DB_PORT: '1521'
      BASE_DB_SID: ORCL
      BASE_DB_USERNAME: idsyncuser
      BASE_DB_PASSWORD: tiens
      APP_LOGS: /u01/applogs
      MQ_ORDER_BIZZNAME: global_data_sync_orders
      MQ_CUST_BIZZNAME: global_data_sync_users
      APPKEY: 1028YA2MNW7VAUHF
      ORDER_COUNT: '100'
      CUST_COUNT: '50'
      GDS_RECEIVER_PORT_8018_TCP_PORT: '8018'
      GDS_RECEIVER_PORT_8018_TCP_PORT: 172.16.129.141 
    stdin_open: true
    tty: true
    links:
    - RECEIVER:GDS_RECEIVER
    ports:
    - 8019:8018/tcp
  RECEIVER:
    image: gds-receiver:1.0.0
    environment:
      DB_IP: 10.1.2.98
      DB_PORT: '1521'
      DB_SID: HQDATA
      DB_USERNAME: system
      DB_PASSWORD: jsbsysdba
      APP_LOGS: /u01/applogs
    stdin_open: true
    tty: true
    ports:
    - 8018:8018/tcp
